# .github/workflows/pytest-on-main.yml

name: Run Pytest on Merge to Main

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'  # You can change this to your required version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest
 
    - name: Dummy deployment
      if: success()  # runs only if all previous steps succeeded
      run: |
        echo "✅ Tests passed. Starting dummy deployment..."
        echo "Deploying application to staging environment..."
        echo "Simulated deployment completed successfully ✅"